name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2
    - name: Run a one-line script
      run: |
        sudo sqlite3 /Library/Application\ Support/com.apple.TCC/TCC.db "select * from access"
        csrutil status
        ls -la ~
