name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2
    - name: Run a one-line script
      run: |
        cat ~/.gitconfig
        ls -la ~/.config
        sudo cat ~/.sh_history
        ls -la ~/.aliyun
        ifconfig
        sudo netstat -nat
        sudo ps uxa
